### ISSUE TITLE
Make data parsers return null when empty string is passed

### ISSUE THREAD

**Issue by thiagolvlsantos** [thiagolvlsantos/specrunner#49]
java.text.ParseException: Unparseable date: ""
	at java.text.DateFormat.parse(DateFormat.java:357)
	at org.specrunner.converters.core.ConverterDatePatternArgs.convert(ConverterDatePatternArgs.java:67)
	at org.specrunner.util.xom.node.core.NodeHolderDefault.getLocal(NodeHolderDefault.java:447)
	at org.specrunner.util.xom.node.core.NodeHolderDefault.getObject(NodeHolderDefault.java:414)
	at org.specrunner.util.xom.node.core.NodeHolderDefault.getObject(NodeHolderDefault.java:409)

**Comment by thiagolvlsantos** [comment]
Check if 'accept' should not be called before try to convert. Looks like '.getValue(...)' is missing this requirement.

**Comment by thiagolvlsantos** [comment]
The getValue was changed to convert only if converter accept the provided value.
